name: Make Recovery

on:
  workflow_dispatch:
    inputs:
      LIBRARY_NAME:
        description: 'LIBRARY_NAME'
        required: true
        default: 'omni'
      LIBRARY_URL:
        description: 'LIBRARY_URL'
        required: true
        default: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git'
      LIBRARY_BRANCH:
        description: 'LIBRARY_BRANCH'
        required: true
        default: 'twrp-9.0'
      DEVICE_URL:
        description: 'DEVICE_URL'
        required: true
        default: 'https://github.com/samsingsangsung/device_samsung_m40'
      DEVICE_BRANCH:
        description: 'DEVICE_BRANCH'
        required: true
        default: 'twrp-9.0'
      DEVICE_PATH:
        description: 'DEVICE_PATH'
        required: true
        default: 'device/samsung/m40'
      DEVICE_NAME:
        description: 'DEVICE_NAME'
        required: true
        default: 'm40'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-22.04
    
    steps:
    - name: Check Out
      uses: actions/checkout@v3
      
    - name: Prepare the environment
      run: |
        docker rmi $(docker images -q) || true
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d
        sudo apt -y purge --ignore-missing azure-cli dotnet* powershell openjdk* mysql* php* 2>/dev/null || true
        sudo apt -y autoremove --purge
        sudo apt -y autoclean
        sudo apt clean
        sudo apt update
        sudo apt -y upgrade
        sudo apt -y install git-core gnupg flex bison gperf build-essential zip curl tree jq bc ccache bash-completion zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev lib32z-dev x11proto-core-dev libx11-dev libgl1-mesa-dev libxml2 libxml2-utils liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libbz2-dev xsltproc unzip lzop pngcrush rsync schedtool squashfs-tools imagemagick lzma ncftp python3 python-is-python3 openjdk-8-jdk qemu-user-static libncurses5
      
    - name: Set variables
      id: var
      run: echo "date=$(date +%F)" >> $GITHUB_OUTPUT
      
    - name: Install repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH
      
    - name: Initialize repo
      id: pwd
      run: |
        mkdir workspace
        cd workspace
        echo "pwd=$(pwd)" >> $GITHUB_OUTPUT
        git config --global user.name "Hikaru's Action-Build-Bot"
        git config --global user.email "Android@teio.tk"
        repo init --depth=1 -u ${{ github.event.inputs.LIBRARY_URL }} -b ${{ github.event.inputs.LIBRARY_BRANCH }}
          
    - name: Repo Sync
      run: |
        cd workspace
        repo sync -j$(nproc --all) -f --force-sync
        ls -al
      
    - name: Clone device
      run: |
        cd ${{ steps.pwd.outputs.pwd }}
        git clone ${{ github.event.inputs.DEVICE_URL }} -b ${{ github.event.inputs.DEVICE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}

    - name: Building
      run: |
        cd ${{ steps.pwd.outputs.pwd }}
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch ${{ github.event.inputs.LIBRARY_NAME }}_${{ github.event.inputs.DEVICE_NAME }}-eng 
        make clean
        make recoveryimage -j$(nproc --all)        
      
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/recovery.img
        name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: Recovery for ${{ github.event.inputs.DEVICE_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
